name: pipeline

on:
    push:

jobs: 
  primer-pipeline:
    runs-on: ubuntu-latest
    container:
      image: openjdk:11
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ant
      run: apt-get update && apt-get install -y ant

    - name: Build with Ant
      run: ant build 